language: python

python:
  - 3.5

services:
  - redis-server

before_install:
  - export PYTHONPATH=$HOME/builds/ro6ley/midget
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt

script:
  - python midget/manage.py makemigrations api --settings=settings.testing
  - python midget/manage.py migrate --settings=settings.testing
  - coverage run --source=midget midget/manage.py test --settings=settings.testing midget/api --noinput

# run coveralls after successful tests
after_success:
  - coveralls
